apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: evdr-system
  labels:
    app.kubernetes.io/name: hello-service
spec:
  selector:
    app.kubernetes.io/name: hello-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
